services:
  - type: web
    name: iyakuhin-app
    env: static
    staticPublishPath: .
    buildCommand: ""
    headers:
      - path: /data/*.json
        name: Cache-Control
        value: no-cache, must-revalidate
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
